server:
  port: 8080

nacos:
  discovery:
    server-addr: 127.0.0.1:8848
    auto-register: true

spring:
  application:
    name: mini-authz-server
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        id:
          new_generator_mappings: false

mini-authz-server:
  settings:
    salt: "mini-authz-server"

security:
  jwt:
    token:
      private-key: "{\"p\":\"25frgiAiQ5gtlfR_OOAYi26V9Hl2a4iKp3hU3qOfbangg202wXgh7HOVOv4UvxUdqx6K2EIKRMREh7kqqsp-hLH89NVUAZgeifWDlefnSifOuXq0QZZ6rdTg0wpkZwHpfH64iovXxT6_SfWGw3vFxxteQI1r0O7EPoOGJubRB6c\",\"kty\":\"RSA\",\"q\":\"vNF4YRCXB3hz5LhSyaW8Xz3R9O_xsph8gvR4CB5muQStEKeg6K3DNm-3ih1ctAFbYO9kZdSMLW9hURHdpd2GfEojdd-orjHIdbvdbKrn5FRkmE1IhXG8K-XIRprznMtH7jGKMQzsW4NRZ9paz-DxtHyrwydLrn2523J27LaRDnU\",\"d\":\"hviZtKbOR86WA1tl0aDzmWXEfOBK7SH49dVDHpER0GfIvRSTf1YHAQ9i4Ab34pY_4h-x6Wu3boA6DkXnAWeUp-RU8FyTKWCDKmb1VKChnghj7qKyTbm5LA9Z_SRldswpO-g3e4Ekd0uL00vKxpoPMZ71GrILFbEp49nWstxSwTCT-FOB99tJHvzaWoi1N32DAWhEJ0GkNeBqtmY0JDhsSWaTzG61Lfvw9Bx8j77b_dJ1t5CyCAM_OrkFXMx_C-f-vKN-sVTdBbewycVSYZtDSyxrMfxtdpfhEJIB2RJXKvqusxr_5aeMOm-XQvURqo4fTz_41X203jZOKlqSAKNc0Q\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"mini-authz-server\",\"qi\":\"2ueQvCE6cfmBC528Fdn-vdlLXKV7MD_cFNpWRvdFRm21UXJ0pZoJ9Vem36oUldp8OEniuw1qQvyFnOstiWXWKLatfVjjKZ8TOerlGWLhI8JwwBx1fYn9SjnOcZh73lVlTGIiIy7AMJmh6TWIrG94NL1zffx7fhyX5-xDZtlvWck\",\"dp\":\"bKfjVGPqEGBATi7ItK_N9VAmyu0-9z58vRkBhZiYzn58JQvpSBnVT1ZxxNrsERC1uXJHaXJj-lrTPgUVY6UGrUoUzGCyTIektMbS8V3qR_sigwyAHOQEl_b5t_MwcvezPHLHhWZkwaimpkXjBN89oaOdI3vWmW9Lk1MpEh6r14k\",\"alg\":\"RS256\",\"dq\":\"IgLlWS6g1dKnpZJiLzpwZQOAt0slUVNQUlJw8J1xSXCDMBXR0TfDiyGygOlrEm2QJTTZ89HGckS21eCO-Vqe5_J-0rO38bC7-CEf8HwUizd8a0a4gnkLOSkJ21X7_clMKqa3ysAWLyHHXxqg8wME5sryMZP5ePPir5m9vEPieyU\",\"n\":\"ofc_PU4FrLezNcWGZM_POV8PkLlIyK7Z9xXlExQqyzx7lXOCu3xxnozF4eC0yua6PkQZbg81xn4reUOSH4MBQ1z5gacC5-7iTf2BSX-5fp4DdtH7q7hLs4DeDkxq43-jo5IHnHEPnHns9quR8zdxLnZvszwEWUTRrvZT48bqHePmsjsIeKT5GgPRk9ApbfKqYBwThYCVaa1KnOEM8Z0UazLTZ3TQZDSvw7j_LSPmNu5JiPjz-UTfJavKeg-ZP3nHyqpzEsCpM2uGSRyq-DJwDh6EsFBmHCRmLSk6jCK4QWmshwAZzttK8entkfPEDbatCLszQLlPDIvPK9Aw-4qhUw\"}"
      public-key: "{\"kty\":\"RSA\",\"e\":\"AQAB\",\"use\":\"sig\",\"kid\":\"mini-authz-server\",\"alg\":\"RS256\",\"n\":\"ofc_PU4FrLezNcWGZM_POV8PkLlIyK7Z9xXlExQqyzx7lXOCu3xxnozF4eC0yua6PkQZbg81xn4reUOSH4MBQ1z5gacC5-7iTf2BSX-5fp4DdtH7q7hLs4DeDkxq43-jo5IHnHEPnHns9quR8zdxLnZvszwEWUTRrvZT48bqHePmsjsIeKT5GgPRk9ApbfKqYBwThYCVaa1KnOEM8Z0UazLTZ3TQZDSvw7j_LSPmNu5JiPjz-UTfJavKeg-ZP3nHyqpzEsCpM2uGSRyq-DJwDh6EsFBmHCRmLSk6jCK4QWmshwAZzttK8entkfPEDbatCLszQLlPDIvPK9Aw-4qhUw\"}"
      kid: mini-authz-server
      issuer: mini-authz-server@example.com
      expire-minute: 60