# This deployment use k8s Service as dynamic endpoint discovery.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-authz-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-authz-server
  template:
    metadata:
      labels:
        app: mini-authz-server
    spec:
      containers:
        - image: specialyang/mini-authz-server
          imagePullPolicy: Always
          name: main
---
apiVersion: v1
kind: Service
metadata:
  name: mini-authz-server
spec:
  spec:
    ports:
      - port: 9090
        targetPort: 8080
        protocol: TCP
    selector:
      app: mini-authz-server

